### ISSUE TITLE
Issues Collection | 问题收集帖

### ISSUE THREAD

**Issue by HowToDoThis** [MoeMod/CSMoE#134]
## About This Issues | 关于这个Issues
Mainly language are used in English, Chinese just a assistant to people who want to find the post quickly. (Not much people watching this I think)
主要用语为英文，中文只是辅助查找用途。（虽然没有很多人会看）
## [English]
I think we need a issue collection post to collecting game issues and let developers or users known whether founded and fixed, so I created this. Feel free to telling us if you found the issue that we haven't found and fix yet.

## [中文]
我认为我们需要一个问题收集帖来收集游戏问题，并让开发人员或用户知道是否已创建和修复，因此我创建了这个。如果您发现了我们尚未发现并还没解决的问题，请随时告诉我们。

## Known Issues | 已知问题
- [x] Bot Unable Created (Fixed in branch - WinRT https://github.com/MoeMod/CSMoE/commit/51e0e9bf7143a35319ef12bfe74d199d5c916b4f)
- [ ] Bot Navigation Problem (#62 ) 
- [x] iOS : IPA Size (#136 )
- [ ] In-Game Weapon Bar Improvement (#119 )
- [x] Bullet Hole (#101 )
- [ ] Android : App unable install due not signed (#155 #141 )
- [ ] Windows 10 : App unable install normally due not signed 
(As usual, we can directly install with store or .appx, but our sign are not officially trusted by Microsoft, user need to install our cert in Trusted Cert or something like that, then user can install the .appx)
- [ ] Code-signing Issues (#141 )

These Problems are in WinRT (#133 )
- [x] Mouse Input Bug (WIP)
- [ ] Startup music kinda broken
- [ ] Touch Keyboard on MainUI Immediately Show and Collapse
- [ ] Random Crash while IME Enabled (?)
- [x] Window Size | Fullscreen | Maximized Not Saved

## Enhancements | 功能/优化
- [x] #157 
- [x] #146 
- [x] #119 
- [x] #88 
- [ ] #113 Add Damage Indicator (Buff Damage Hud/CSO new feature)
- [ ] #223 GLES2 Support

## CPU Support | CPU支持
- [ ] #193 aarch64 support
- [ ] Apple M1 (arm64) support
- [ ] #214 arm64-v8a support

**Comment by MoeMod** [comment]
fixed in v22-citrus
