### ISSUE TITLE
v19 roadmap / TODO list

### ISSUE THREAD

**Issue by MoeMod** [MoeMod/CSMoE#40]
- [ ]  Gameplay : GunDeath
- [x] New Weapon for GunDeath : TAR-21
- [ ] New Weapon for GunDeath : AN94
- [ ] New Weapon for GunDeath : M16A4
- [x] New Weapon for GunDeath : WA2000
- [x] New Weapon for GunDeath : M95
- [x] New Weapon for GunDeath : AS50
- [x] New Weapon for GunDeath : XM8
- [x] New Weapon for GunDeath : SCAR
- [ ] New Weapon for GunDeath : XM2010
- [x] New Weapon for GunDeath : K1A
- [ ] New Weapon for GunDeath : USAS-12
- [ ] New Weapon for GunDeath : VSK-98
- [ ] New Weapon for GunDeath : STG44
- [x] New Weapon for GunDeath : MP7A1
- [x] New Weapon for GunDeath : Thompson
- [x] New Weapon for GunDeath : M1887 Winchester
- [ ] New Weapon for GunDeath : QBB95
- [ ] New Weapon for GunDeath : MG36
- [x] New Weapon for GunDeath : M60E4
- [x] New Weapon for GunDeath : Kriss
- [x] New Weapon for GunDeath : Anaconda
- [x] New Weapon for GunDeath : Infinity Sliver
- [x] New Weapon for GunDeath : Infinity Black
- [x] New Weapon for ZB3 : SVDEX
- [ ] Randomize weapon in ZB3
- [x] An new knife to replace skullaxe
- [x] An new zombie class to replace / extend the original one
- [x] New touch gestures to switch weapons

**Comment by MoeMod** [comment]
won't fix. GD is removed
